packaging_format = 2

id = "tinyfilemanager"
name = "Tiny File Manager"
description.en = "Web based file manager"
description.fr = "Gestionnaire de fichiers simple"

version = "2.5.0~ynh1"

maintainers = ["Jarod5001"]

[upstream]
license = "GPL-3.0"
website = "https://tinyfilemanager.github.io/"
demo = "https://tinyfilemanager.github.io/demo/"
admindoc = "https://github.com/prasathmani/tinyfilemanager/wiki"
userdoc = "https://github.com/prasathmani/tinyfilemanager"
code = "https://github.com/prasathmani/tinyfilemanager"

[integration]
yunohost = ">= 11.1.13"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/tinyfilemanager"

[resources]
        [resources.sources.main]
        url = "https://github.com/prasathmani/tinyfilemanager/archive/refs/tags/2.5.0.tar.gz"
        sha256 = "847a280ca8e1c31a4a39884da8f301ee77ff1885cec359a996ed3cd1430c8ffd"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php8.0-xml php8.0-cli php8.0-iconv php8.0-bz2 php8.0-zip php8.0-fileinfo php8.0-mbstring"
